[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]
via_ir = true
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
# Mantle Sepolia Testnet
mantle_sepolia = "https://mantle-sepolia.g.alchemy.com/v2/cpenwKf_vUc59UKfsx5FUumCtZ_bSU_W"
testnet = "${RPC_URL}"

# Mantle Mainnet
mantle_mainnet = "https://rpc.mantle.xyz"
mainnet = "https://rpc.mantle.xyz"

[etherscan]
# Mantle block explorer
mantle_sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://sepolia.mantlescan.xyz/api" }
mantle_mainnet = { key = "${ETHERSCAN_API_KEY}", url = "https://mantlescan.xyz/api" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
